
// require('./03_destructuring')
// require('./04_string')
// require('./05_regular_express')
// require('./06_number')
// require('./07_function')
// require('./08_array')
// require('./09_object')
// require('./11_symbol')
// require('./12_set_map')
// require('./15_promise')
// require('./16_iterator')
// require('./17_generator')
// require('./19_async')
require('./20_class')
